server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://xmen-mutant-db.czxzee1yluwl.us-east-1.rds.amazonaws.com:3306/xmen-mutant-db
    username: admin
    password: xmen-db-2022-password
    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      hibernate:
        SQL: debug
mutant:
  acceptance:
    limitSequencesOfNitrogenousBasesForHuman: 1
    limitOfElementsFollowedInTheSequences: 4

#Docker config
#server:
#  port: 8080
#spring:
#  datasource:
#    url: jdbc:mysql://${DB_HOSTNAME}:${DB_PORT}/${DB_DATABASE}
#    username: ${DB_USER}
#    password: ${DB_PASSWORD}
#    driver-class-name: com.mysql.cj.jdbc.NonRegisteringDriver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#logging:
#  level:
#    org:
#      hibernate:
#        SQL: debug
#mutant:
#  acceptance:
#    limitSequencesOfNitrogenousBasesForHuman: 1
#    limitOfElementsFollowedInTheSequences: 4